### ISSUE TITLE
Virus report is here

### ISSUE THREAD

**Issue by Lucky390163** [rumboalla/apkupdater#484] opened 2023-11-15 02:50 UTC
@![Screenshot_20231115_081931_VirusTotal Mobile.jpg](https://github.com/rumboalla/apkupdater/assets/115852216/f35c0ce4-e4ec-43c5-be0e-5f3c314fa6ef)

![Screenshot_20231115_081931_VirusTotal Mobile.jpg](https://github.com/rumboalla/apkupdater/assets/115852216/b7b03f24-9790-4df7-a79c-41834c32460f)

By Virus Total

**Comment by AnonymousWP** [comment] 2023-11-21 15:28
Duplicate of https://github.com/rumboalla/apkupdater/issues/465. Close this one and continue there.

**Closed as completed** 2023-11-24 09:56 UTC
