### ISSUE TITLE
Hide columns sliders when android TV UI is enabled 

### ISSUE THREAD

**Issue by maj113** [rumboalla/apkupdater#420] opened 2023-08-24 20:30 UTC
Since those sliders don't do anything when it's enabled it may be a good idea to hide them especially since people on ATV will probably never actually interact with those anyways

**Comment by rumboalla** [comment] 2023-08-24 22:23
It is on my todo. Closing since this is not a bug.

**Closed as completed by rumboalla** 2023-08-24 22:23 UTC

**Comment by maj113** [comment] 2023-08-25 09:53
> It is on my todo. Closing since this is not a bug.

My bad, didn't see the discussion page
