### ISSUE TITLE
getUpdatesAsync error.

### ISSUE THREAD

**Issue by gidano** [rumboalla/apkupdater#351] opened 2021-03-28 17:01 UTC
Hi,
The app has been rhapsodic for weeks, but hasn't worked at all for days.
Server-side or API error, or what kind of problem may be in the background?
To the best of my knowledge, this is the only app that also reads data from four app stores, its use is very lacking!
My system is Android 11, I hope this is not the cause of the error?!
 
Thx,
gidano

![Screenshot_20210328-185615_APKUpdater](https://user-images.githubusercontent.com/4068977/112760534-971ebc00-8ff7-11eb-953e-33f3e386bbfd.png)

**Comment by fokaias** [comment] 2021-03-29 13:05
Feeling pretty rhapsodic, too. I've had this issue on Android 9 and 10 for several days now. One of Google's tricks? A fix would be nice!

**Comment by hemker** [comment] 2021-03-29 13:09
Took a quick look into the code. Might be due to API changes. ApkUpdater uses this [library](https://github.com/whyorean/playstore-api-v2), which seems outdated. Could be the reason for ongoing problems with GooglePlay. There are more recent versions of Playstore APIs, but this might need more time to implement.

**Comment by dfg369853** [comment] 2021-03-29 13:53
Turn off Google play. Aurora Dispensers Disabled. Because they are used to communicate with the GP.

**Comment by hemker** [comment] 2021-03-29 14:22
@dfg369853 Do you mean that the aurora dispensers no longer work? Did they change the API or anything else?

**Comment by dfg369853** [comment] 2021-03-29 15:46
> @dfg369853 Do you mean that the aurora dispensers no longer work? Did they change the API or anything else?

Hi, developer apkGrabber 😂! Yes. In this program connection in Google play will use Aurora Dispensers, but we will be turnoff , because support for the Aurora Store 3 has ended, and these dispensers were used in it.  Aurora version 4 has new dispensers.

Sorry uncorrect English. I speak Russian good, and English is no good

**Comment by fokaias** [comment] 2021-03-29 16:34
For the record, APKGrabber (1.7.0) now delights us with a similar problem: 'Error 401: Unauthorized.'

**Comment by dfg369853** [comment] 2021-03-29 18:33
> For the record, APKGrabber (1.7.0) now delights us with a similar problem: 'Error 401: Unauthorized.'

Yes. Apkgrabber too use Aurora Dispenser.

**Comment by AnonymousWP** [comment] 2021-04-01 22:13
Having this issue as well since about a week, if not longer. I suppose the developer of this app has to release an app update in order to make the app work with Google's changed back-end (API).

**Comment by dfg369853** [comment] 2021-04-02 05:11
> Having this issue as well since about a week, if not longer. I suppose the developer of this app has to release an app update in order to make the app work with Google's changed back-end (API).

need to contact the developer of Aurora, it's not about the new google api! Aurora Dispenser is new.

**Comment by g00nix** [comment] 2021-05-10 22:14
I can confirm this bug on LineageOS 18.1, running Android 11.

**Comment by gidano** [comment] 2021-05-11 06:49
Excuse me, has this project stopped?
Nothing has happened in a long time...
Do I have to look for another solution?

**Comment by g00nix** [comment] 2021-05-11 07:56
> Do I have to look for another solution?

No, you can just disable the Google Play in the settings of ApkUpdater and it will work.

**Comment by fokaias** [comment] 2021-05-11 08:14
Claiming that disabling its main functionality - and appeal - will make it 'work' is a bit of a stretch. I've switched to Aurora Store and am quite content with it for now. But of course it would be great if someone could fix or fork this little gem.

**Comment by g00nix** [comment] 2021-05-11 09:59
> Claiming that disabling its main functionality - and appeal - will make it 'work' is a bit of a stretch.

The main functionality and appeal of this app is not being able to work with Google Play, but the ability to replace Google Play. If you have an Android phone without Google services and you installed all apks from a secure source (like apkmirror or fdroid), you will also need an app to update all other apps. THAT is the main appeal of ApkUpdated: The ability to update software installed from ApkMirror without the requirement Google Play or any other shady software.

So you will still have the main functionality and appeal of your smartphone and of ApkUpdater even without any Google Services.

**Comment by fokaias** [comment] 2021-05-11 12:16
For you, perhaps. There are good reasons for not wanting Google on one's device; there are also valid reasons for wanting to obtain one's updates directly from the Play Store nevertheless.

**Comment by Olf0** [comment] 2021-09-06 00:42
While issue #353 seems to be a duplicate of this one, @DavidBurela's [comment there does add a new aspect](https://github.com/rumboalla/apkupdater/issues/353#issuecomment-821962809):
The lack of proper error reporting and handling makes it hard to comprehend, that only a single repository fails, and the issue can be resolved by disabling that single repository.

**Comment by obsessedlady** [comment] 2021-09-07 23:58
Same error happens with only APKMirror activated. I guess the app just doesn't work anymore

**Comment by Olf0** [comment] 2021-09-08 00:50
> Same error happens with only APKMirror activated. I guess the app just doesn't work anymore

Well, this is *not* the case for me (see issue #365).
Plus: Why should the app proper stop working?  IMO it is always server side (API) changes causing that, if the local environment stays the same (i.e., no OS updates etc.).

**Comment by madroots** [comment] 2022-07-03 17:13
Is this project dead? It still wont work with playstore...

**Comment by StormProductionsMusic** [comment] 2022-12-16 18:41
Any alternative of this app that actually allows usage of PlayStore?

**Comment by Olf0** [comment] 2022-12-17 00:57
Aurora Store from F-Droid: https://f-droid.org/en/packages/com.aurora.store/

**Closed as completed** 2023-07-10 12:32 UTC
