### ISSUE TITLE
Error occuring when trying to check for updates

### ISSUE THREAD

**Issue by gnpaone** [rumboalla/apkupdater#364] opened 2021-09-05 14:26 UTC
Recently, when trying to check for updates it gives updates sync error. Please solve the issue
![Screenshot_2021-09-05-19-53-50-439_com apkupdater](https://user-images.githubusercontent.com/78990165/132130472-e3a279ea-5a38-4333-a3de-b7d7e6189fad.jpg)

**Comment by Olf0** [comment] 2021-09-06 00:33
Duplicate of issue #351!

**Closed as completed** 2023-07-10 12:32 UTC
