### ISSUE TITLE
On some Android versions (8, 9) both success and failure messages are received during a successful install

### ISSUE THREAD

**Issue by TechDoctorUK** [rumboalla/apkupdater#409] opened 2023-08-19 21:17 UTC
On Amazon Fire TV cube (Android9), using beta [APKUpdater 3.0.0-beta-04], every update I try to install shows this error:

![image](https://github.com/rumboalla/apkupdater/assets/25614191/8cab6d68-cc3d-44d9-9397-1d34921987d5)

using the beta-03 release, i am able to install updates but the UI doesnt show the current / new version numbers as you can see here:

![image](https://github.com/rumboalla/apkupdater/assets/25614191/a09409da-3b46-486e-a61a-58baa6b37a3b)

Thanks

**Comment by rumboalla** [comment] 2023-08-19 22:03
Looks like you are trying to update an app from F-Droid that was not installed from F-Droid. This means the app signature is different and can't be installed. You should check the logs to see why it failed to install.

**Comment by TechDoctorUK** [comment] 2023-08-20 01:41
The ones I tested were all from Aptoide TV, even though they were originally installed from various websites.

Where can i see the install log ?

**Comment by rumboalla** [comment] 2023-08-20 09:05
> The ones I tested were all from Aptoide TV, even though they were originally installed from various websites.
> 
> Where can i see the install log ?

You can use ```adb logcat *:E```

**Comment by TechDoctorUK** [comment] 2023-08-20 16:11
Upon further investigation, it appears the update is being installed (i noticed this as the app that was showing an update would disappear from the list), even though im still getting the same error. 

I attached the logcat.

Thanks



[cube-error.txt](https://github.com/rumboalla/apkupdater/files/12388584/cube-error.txt)

**Comment by rumboalla** [comment] 2023-08-20 17:09
> Upon further investigation, it appears the update is being installed (i noticed this as the app that was showing an update would disappear from the list), even though im still getting the same error.
> 
> I attached the logcat.
> 
> Thanks
> 
> [cube-error.txt](https://github.com/rumboalla/apkupdater/files/12388584/cube-error.txt)

And you never get the success message?
I don't see anything in the logs, you have to take them during the installation.

**Comment by TechDoctorUK** [comment] 2023-08-20 17:29
(i never saw any success message )

I turned the log on,

Clicked on "Install app" next to Plex TV.

The screen changed to "do you want to install the update" - i clicked on install and i see the error straight away.

A few seconds later Plex disappears from the list.

I can see in my installed apps, the latest version of Plex is installed.

I stopped the log and attached
[cube-error-2.txt](https://github.com/rumboalla/apkupdater/files/12388766/cube-error-2.txt)

**Comment by rumboalla** [comment] 2023-08-20 18:56
> (i never saw any success message )
> 
> I turned the log on,
> 
> Clicked on "Install app" next to Plex TV.
> 
> The screen changed to "do you want to install the update" - i clicked on install and i see the error straight away.
> 
> A few seconds later Plex disappears from the list.
> 
> I can see in my installed apps, the latest version of Plex is installed.
> 
> I stopped the log and attached [cube-error-2.txt](https://github.com/rumboalla/apkupdater/files/12388766/cube-error-2.txt)

It looks like a failure arrives first followed by a success. I've been able to reproduce this on Android 8.

**Comment by rumboalla** [comment] 2023-08-20 22:13
This should be fixed with new release

**Closed as completed by rumboalla** 2023-08-20 22:13 UTC
Labels: bug
